# Generated by Django 3.2.8 on 2021-10-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211015_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='language',
        ),
        migrations.RemoveField(
            model_name='film',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='film',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='film',
            name='released',
        ),
        migrations.RemoveField(
            model_name='film',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='film',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
    ]
