# Generated by Django 3.2.8 on 2021-10-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211015_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='Ratings',
        ),
    ]
