# Generated by Django 3.2.8 on 2021-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_film_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
