# Generated by Django 3.2.8 on 2021-10-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Plot',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=200)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
            ],
        ),
    ]
