# Generated by Django 3.2.8 on 2021-10-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211018_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='totalSeasons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='BoxOffice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='DVD',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='Metascore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='Production',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='Type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='Website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='Year',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdbID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdbRating',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdbVotes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='api.film'),
        ),
    ]
