# Generated by Django 3.2.8 on 2021-10-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_film_metascore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='film_id',
            new_name='film',
        ),
    ]
