# Generated by Django 3.2.6 on 2021-10-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211026_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'Ratings'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='film',
            new_name='movie',
        ),
    ]
